baseURL: 'https://example.org/'
languageCode: 'ko-kr'
title: 'HyunhoLee'
theme: 'PaperMod'
params:
  homeInfoParams:
    Title: ì•ˆë…•í•˜ì„¸ìš”! ğŸ™‹â€â™‚ï¸
    Content: ê°œë°œí•˜ë©° ë°°ìš´ ì§€ì‹ì„ ì •ë¦¬í•˜ëŠ” ê¸°ìˆ  ë¸”ë¡œê·¸ì…ë‹ˆë‹¤.